name: example_workcell
services:
  ###########
  # Modules #
  ###########
  ur_module:
    container_name: ur_module
    image: ghcr.io/ad-sdl/ur_module:latest
    command: python -m ur_rest_node --port 3011 --ur_ip ${UR_IP}
    ports:
      - 3011:3011
  vention_rail_module:
    container_name: vention_rail_module
    image: ghcr.io/ad-sdl/vention_rail_module:latest
    command: python -m rail_rest_node --port 3022 --rail_ip ${RAIL_IP}
    ports:
      - 3022:3022
  #####################
  # WEI Core Services #
  #####################
  aarl200_server:
    image: ghcr.io/ad-sdl/wei:latest
    container_name: aarl200_server
    ports:
      - 8000:8000
    volumes:
      - ./workcell_defs:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME}
    depends_on:
      - aarl200_redis
  aarl200_redis:
    image: redis
    container_name: aarl200_redis
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DIR}:/data
    command: redis-server --save 60 1 --loglevel warning
