services:
  aarl200_mongodb:
    container_name: aarl200_mongodb
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci/mongodb:/data/db

  aarl200_redis:
    container_name: aarl200_redis
    image: redis:7.4
    ports:
      - 6379:6379
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci/redis:/data

  aarl200_postgres:
    container_name: aarl200_postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=aarl200
      - POSTGRES_PASSWORD=aarl200
      - POSTGRES_DB=resources
    ports:
      - 5432:5432
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci/postgres:/var/lib/postgresql/data
