services:
  #####################
  # MADSci Managers #
  #####################
  aarl200_event_manager:
    container_name: aarl200_event_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ../managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci:/home/madsci/.madsci/
    command: python -m madsci.event_manager.event_server --definition managers/aarl200_event_manager.manager.yaml
    depends_on:
      - aarl200_mongodb

  aarl200_wc_manager:
    container_name: aarl200_wc_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ../workcells:/home/madsci/workcells
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci:/home/madsci/.madsci/
    command: python -m madsci.workcell_manager.workcell_server --definition workcells/aarl200_workcell.manager.yaml
    restart: on-failure
    depends_on:
      - aarl200_redis
      - aarl200_event_manager
      - aarl200_data_manager
      - aarl200_mongodb

  aarl200_lab_manager:
    container_name: aarl200_lab_manager
    image: ghcr.io/ad-sdl/madsci_dashboard:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ../managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci:/home/madsci/.madsci/
    command: python -m madsci.squid.lab_server --definition managers/aarl200_lab_manager.manager.yaml
    restart: on-failure
    depends_on:
      - aarl200_redis
      - aarl200_event_manager
      - aarl200_data_manager

  aarl200_resource_manager:
    container_name: aarl200_resource_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ../managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci:/home/madsci/.madsci/
    command: python -m madsci.resource_manager.resource_server --definition managers/aarl200_resource_manager.manager.yaml
    depends_on:
      - aarl200_postgres
      - aarl200_event_manager

  aarl200_experiment_manager:
    container_name: aarl200_experiment_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    restart: on-failure
    volumes:
      - ../managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci:/home/madsci/.madsci/
    command: python -m madsci.experiment_manager.experiment_server --definition managers/aarl200_experiment_manager.manager.yaml
    depends_on:
      - aarl200_mongodb
      - aarl200_event_manager

  aarl200_data_manager:
    container_name: aarl200_data_manager
    image: ghcr.io/ad-sdl/madsci:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    network_mode: host
    volumes:
      - ../managers:/home/madsci/managers
      - ${LOCAL_WORKSPACE_FOLDER:-../}.madsci:/home/madsci/.madsci/
    command: python -m madsci.data_manager.data_server --definition managers/aarl200_data_manager.manager.yaml
    depends_on:
      - aarl200_mongodb
      - aarl200_event_manager
