services:
  ###########
  # Nodes #
  ###########
  ur_aarl200:
      container_name: ur_aarl200
      image: ghcr.io/ad-sdl/ur_module:latest
      environment:
      - USER_ID=1000
      - GROUP_ID=1000
      command: python -m ur_rest_node --definition nodes/ur_aarl200.node.yaml
      network_mode: host
      volumes:
      - ../nodes:/home/madsci/nodes
    
  vention_rail_module:
    container_name: vention_rail_aarl200
    image: ghcr.io/ad-sdl/vention_rail_module:latest
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    command: python -m rail_rest_node --definition nodes/vention_rail_aarl200.node.yaml
    network_mode: host
    volumes:
      - ../nodes:/home/madsci/nodes
  